### ISSUE TITLE
Granular filewatch updates

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#226]
### ~The shadow tree~ The Dom

(So i did rename this to be "the dom", even if the name does not quite fit)

Every treemacs buffer possesses a backing data structure that is similar to a limited dom, except that I
call it the shadow-tree, since it shadows the visible file tree(s). Specifically it mirrors the structure of expanded directories and tag groups. Every shadow-node in that tree is a struct that is made up of the following fields:

 * `key` - The node's unique key, usually its absolute path. This makes every node accessible in O(1) time through     the hash table called the shadow-index (likewise unique in every treemacs buffer)
 * `parent` - The parent shadow-node, if any.
 * `children` - The immediate child nodes, if any.
 * `position` - A marker to the node's position. The same object as `treemacs-current-btn` would return.    Not all nodes have a position. When a node is collapsed while it has expanded children of its own it is not removed from the shadow-tree. Instead its position is deleted and it is marked as closed. This way when the node is reopened its children will be reopened as well.
 * `closed` - Marker for closed nodes. See above.
 * `refresh-flag` - Marker for directories in need of being refreshed.

### The filewatch callback setup

With `filewatch-mode` enabled treemacs will put under watch all directories that it displays, calling treemacs' callback function for every change in the watched directories. The exact makeup of the callback event argument can be read up in the docs for `file-notify-add-watch`.

When it receives an event treemacs first decides if the event is relevant at all. This means it will ignore changes to lock or backup files. A file being *changed* is only of interest when `treemacs-git-mode` is enabled. The decision is ultimately user-configurable by means of `treemacs-ignored-file-predicates`. When a file was deleted or renamed treemacs will also update the shadow-trees in every buffer.

As a last step treemacs will set the refresh flag of the directory the change *happened in* and start a timer to start a refresh after a delay of `treemacs-file-event-delay` ms.

### Recursive Descent Refresh

On a refresh treemacs will - for every buffer, for every project in the buffer - begin descending its shadow tree. If a shadow-node's refresh flag is not set the descent continues recursively. If it is then treemacs will first do the aequivalent of moving to the node's position and pressing TAB twice, so as to refresh that directory and all its children. Since nodes below the one that was just refreshed may have their refresh flags set as well the descent will continue to reset these flags. A refresh therefore requires a full shadow tree traversal.

### Weaknesses of the current approach

While a major improvement over the very first version of `filewatch-mode`, which would simply refresh the entire project, the current system lacks accuracy and is typically overkill. Not only does it still refresh full projects - if only a file at the root was changed - refreshing at the directory level is still doing too much work when only one, or a few files have changed. The most common reason for filewatch-mode to strike is probably saving  - again - the one file you are currently editing.

### Fine grained changes

It'd be much more appropriate to apply only the actual changes and do the least amount of work necessary. So, given a set of changes, treemacs should learn to apply them one by one, as the amount of work needed for this can, in most cases, be expected to be much smaller than a hard refresh of an entire directory, especially if that directory is close to the root and refreshing it also entails reopening all its children.

The refresh-flag, currently used just a boolean, can be changed to instead hold a list of files that were changed and the type of the change for a given directory. Upon a refresh descent treemacs could then make a decision whether to apply the changes one by one or do a full directory refresh based on the count or makeup of the refresh list.

Different changes must be applied in different ways, and some are certainly more difficult than others. Deleting a file is simpler than creating one since the created file needs to be displayed in the right position, which is particularly challenging due to `treemacs-resort`. All in all there's the following cases to consider:

 * [x] Deletion of a file
 * [x] Deletion of a directory
 * [x] Creation of a new file or directory
 * [x] Renaming of a file or directory
 * [x] Change to a file, requirung querying its git status

In case of `git-mode` new files must be fontified accordingly.

### Don't get stuck

The last time I implemented a major change I worked on it on a long-term basis, wanting to push in one go. This had the consequence that my published code and my wip code diverged to the point that by the end of it I couldn't even publish my bug fixes and needed to tell people to wait for the new feature to be finished first. Let's not do that this time. No non-functional intermediate state this time, the changes should come in small steps and be able to go on master.

**Comment by Alexander-Miller** [comment]
Have the basics covered now. Next up is making sure that things work with flattened nodes.

 * [ ] Deletion of a file
 * [ ] Deletion of a directory
 * [ ] Creation of a new file or directory
 * [ ] Renaming of a file or directory
 * [ ] Change to a file, requiring querying its git status

**Comment by Alexander-Miller** [comment]
I think we're finally through here.
