### ISSUE TITLE
Workspace Management

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#247]
As of now the idea of workspaces in treemacs is embryonic to the point that the word "worspace" may as well be replaced with "the list of your projects" in the code and the documentation and nothing would change. So let's go over how I plan to change that.

First the basic goals: workspaces should
  1. group projects arbitrarily
  2. provide convenient display - every treemacs buffer should display some given workspace
  3. have the right interface to administer all that, the usual CRUD operations and some "display
     that" commands
  4. provide the right plumbing to programmatically interface from other packages

A small part of that is done already, the current project add/remove commands already call into appropriate workspace functions. Still there's quite a bit more to do. The first obstacle is making sure that workspaces are properly localized. `(treemacs-current-workspace)` returns a global value, I need to make sure that 1) the value is buffer-local, and 2) the function is then only called in the right buffer.

Then there's the slow buildup of all the required nuts and bolts: create and delete workspaces (make sure you cannot delete the last workspace), change displayed workspace, add, remove, copy and move projects to and between workspaces, also some utilities like `get-all-workspaces/projects`, first
just the functions then with some proper UI, sensible keymaps and a good place to show the ini layout from https://github.com/Alexander-Miller/treemacs/issues/199.

The answer of which workspace to display first has been nicely answered in https://github.com/Alexander-Miller/treemacs/issues/213. First try to find the right project for the current buffer, if nothing fits show the "Default" workspace, if there is no default just show the first one in the list. There is the small edge case of a project being part of multiple workspace, but I see no issue in just picking the *first* workspace that fits.

That should be enough for now. Next in line: think up (some of) the details of the api, come up with a keymap/UI and split this thing into some sensible smaller tasks.

Pinging some people who might be interested in this: @nlamirault @dakra @mciocchi

**Comment by Alexander-Miller** [comment]
Let's think up the api we'll need. Every point will translate into its own function, plus the
namespace prefix. Some already exist and just need to be renamed.
 - `create-workspace`
 - `delete-workspace`
 - `add-project-to-workspace`
 - `remove-project-from-workspace`
 - `move-project-into-workspace`
 - `copy-project-into-workspace` (could be hidden behind prefix arg)
 - `workspace-list`
 - `projects-list`

These functions will primarily be interactive, there will also be appropriate internal api for them
to call into when necessary, such that for example next to `add-project-to-workspace` there'll also
be a `(workspace->add-project! workspace project)` function.

Of course that'll ignore a bunch of validations like duplicate names, so the `interactive` should
be designed to be able take all the arguments it needs.

Note on projects in multiple workspaces: Each project object is independent, a new object is created
even when it is copied into another workspace, so e.g. changing the name of one won't affect the
other. That should prevent some ugly edge-cases.

The restriction of a path appearing no more than once in a workspace still applies, and must be
validated accordingly.

**Comment by Alexander-Miller** [comment]
On the matter of persistence format there's two options now. Originally I wanted to use a conf mode file, but I've now come up with a way to use org-mode that doesn't look half bad:


https://imgur.com/a/0TYYykH

What do you think?
(That means you @TimoFreiberg as you weren't *directly amazed* by my conf-mode idea.)

**Comment by TimoFreiberg** [comment]
The org-mode version looks a little bit better imho, mainly because the hierarchy is more visible due to the indentation.
The org-mode version does not require any external dependencies, right?
Sounds like a good candidate.

**Comment by Alexander-Miller** [comment]
Nope, neither version needs any dependencies. Parsing will be a bit crazy, `org-element-parse-buffer` gives me bucket loads of information and I don't even know if that format is stable across versions to the point that I consider writing my own simple parser (it was easy enough for the ini format).

Org-mode will also make actual editing easier - changing the order of your projects or moving between workspaces and all that stuff is already built in.

**Comment by Alexander-Miller** [comment]
A small roadmap to see where things are going:

 - [x] Switch persist format to org-mod
 - [ ] [Basic workspaces](https://github.com/Alexander-Miller/treemacs/issues/250)
 - [ ] [Ability to switch between workspaces](https://github.com/Alexander-Miller/treemacs/issues/251)
 - [ ] [Ability to *locally* switch between workspaces](https://github.com/Alexander-Miller/treemacs/issues/252)
 - [ ] [workspace edit mode](https://github.com/Alexander-Miller/treemacs/issues/253)
 - [ ] [Filling out the API](https://github.com/Alexander-Miller/treemacs/issues/254)
 - [ ] [A good UI for the whole thing](https://github.com/Alexander-Miller/treemacs/issues/255)
 - [ ] [documentation](https://github.com/Alexander-Miller/treemacs/issues/256)

**Comment by Alexander-Miller** [comment]
Some good chunks of the api stand now. I think I've come up with a reasonable api for workspace handling as you can see in https://github.com/Alexander-Miller/treemacs/commit/1267d352288ef20719a1fb87a47ac05e32e79cfa. Basically you'll always have an interactive `treemacs-action` that internally calls a `treemacs-do-action`. The former is responsible for the UI, the latter for input validation and all the internal plumbing and provides feedback that's nicely handled with a `pcase`. 

Right now the separation is not quite as I'd like it to be,  since the do-action functions are currently making sure to update the view. I'll try to put all the ui bits into the interactive parts. If another package wants to handle treemacs' workspaces I'll offer a macro that takes a bunch of do-action calls in its body and then automatically handles bringing the view in line.

**Comment by Alexander-Miller** [comment]
Editing workspace with org-mode is now pushed. If someone who isn't me could try calling `treemacs-edit-workspaces` that'd be great. And go ahead and try and break things, the org file should be properly validated and spit out readable error messages.

**Comment by dakra** [comment]
Thanks. I tried it and works great.

I think `treemacs-finish-edit` should by default be bound to `C-c C-c`.

Unrelated to the edit feature, if start `treemacs` from one of my projects
it should automatically switch to the first workspace that contains this project.
Right now it always switches to the first workspace and then you have to manually
switch to whatever workspace you want.

**Comment by Alexander-Miller** [comment]
>  I tried it and works great.

Best try again. I just introduced a much nicer display of errors with overlays. It's no flycheck, but now you see a message right at the line that's causing the error (so it can't be swallowed up).

> I think treemacs-finish-edit should by default be bound to C-c C-c.

If I can make it work locally, without interfering in org-mode's global keymaps.

> it should automatically switch to the first workspace that contains this project.

That is planned and on the TODO list.

**Comment by dakra** [comment]
Thanks.

I tried it again and looks nice.

It did give me an error message on the wrong line though.

I had

```org
* workspaceA
** projA
 - path :: /home/daniel/proja
```

then I added something wrong:

```org
* workspaceA
** foobar
 - wrong
** projA
 - path :: /home/daniel/proja
```

And after calling `treemacs-finish-edit`
I get `Project name must be followed by path declaration`
in the line of `* projA`.

Also if I call `treemacs-finish-edit` again without doing
anything in between I get the error message overlay double.

**Comment by Alexander-Miller** [comment]
> I get Project name must be followed by path declaration in the line of * projA.

Fixed with https://github.com/Alexander-Miller/treemacs/commit/18e7e61e2db5d4840c8a4f916249a5b1933c11ce

>  I get the error message overlay double.

Fixed with https://github.com/Alexander-Miller/treemacs/commit/466484d4c1b3e0e33d94783a31feb4a345a72602

**Comment by dakra** [comment]
Just tested it again and worked perfectly :+1:

**Comment by andreyorst** [comment]
Is it possible to have different workspaces for different projectile projects, possibly changed automatically?

Because if we compare workspaces from Visual Studio Code, then a workspace usually is a single project that lists several simultaneous root directories, which can be searched all together from one place. Yes thoose roots can be different projects, but usually it is used to add some folders from single project to narrow the search.

Which is kinda what projectile does, except it can't have several simultaneous roots, but Treemacs can, which makes little less sense because of projectile. What I mean is: *adding a project to workspace* in Treemacs is essentially the same thing as *add directory to workspace* in VSCode. But it doesn't affect projectile at all - we still need to jump between projectile projects in order to use fuzzy file finder. Of course if there were another tool that could use Treemacs workspace structure to provide fuzzy file search, instead of projectile it would make sense, and projectile wouldn't be needed anymore.

So instead of changing active project in single workspace when I change project in projectile I would like the workspace itself to represent a project, as I think it means more sense in current state of Emacs being unable to "open directory" or "add directory" like VSCode does even with projectile.

**Comment by Alexander-Miller** [comment]
> Is it possible to have different workspaces for different projectile projects, possibly changed automatically?

Sync options, with projectile or lsp or whatever else, are an option for later.

> Because if we compare workspaces from Visual Studio Code, then a workspace usually is a single project that lists several simultaneous root directories

If that's how you want to use treemacs then you're free to do so. Keep in mind that treemacs has a limitation that a path may only appear in a workspace once.

> which can be searched all together from one place

Basically that's not my job. If there's a way in emacs to search in multiple disparate directories I can integrate it, but it's not a thing for treemacs to do on its own.

> we still need to jump between projectile projects in order to use fuzzy file finder

Are you aware that treemacs is context-sensitive, so to speak? Basically commands like find-files, magit-status or projectile-find-file will use your current position in treemacs as a starting point. So to search another project with projectile just navigate there in treemacs, which can be done in a few keystrokes with C-j/C-k.

**Comment by andreyorst** [comment]
I guess we misunderstood each other.

>Basically that's not my job. If there's a way in emacs to search in multiple disparate directories I can integrate it, but it's not a thing for treemacs to do on its own.

I understand this. I just meant since neither Treemacs, nor Projectile can search for file in several projects at once, having several projects in single workspace is less meaningful compared to VSCode, where you can do search over several projects in single workspace.  (It's more Emacs limitation, because it can't just sit in single directory so we could create a temporary workspace directory and add symbolic links to the project roots there in order to run file search over entire workspace structure as it is done in VSCode.)

So my question is only about ability to treat single project as single workspace and sync active workspace with active projectile project. which you've partially answered with this:

> Sync options, with projectile or lsp or whatever else, are an option for later.

But I didn't knew that:

> Are you aware that treemacs is context-sensitive, so to speak? Basically commands like find-files, magit-status or projectile-find-file will use your current position in treemacs as a starting point.

Which seems to be a good solution too. Thanks

**Comment by Alexander-Miller** [comment]
Other than providing hooks the workspaces feature is done. Let me know what you think and how it works for you.

**Comment by Alexander-Miller** [comment]
I guess we're done.

**Comment by sandinmyjoints** [comment]
What I'd love is to be able to specify a workspace in directory locals and have Treemacs switch to that workspace appropriately, whenever I'm visiting a buffer that those directory locals apply to.

**Comment by Alexander-Miller** [comment]
> What I'd love is to be able to specify a workspace in directory locals

Try `treemacs-override-workspace`. It's not what the variable was
created for, but I think it should do the job.

 > and have Treemacs switch to that workspace appropriately, whenever I'm
 > visiting a buffer that those directory locals apply to.

Once treemacs has selected a workspace for some scope it'll stick around
until you switch it manually. Introducing a select-the-workspace-again
behavior is a new feature - so you should open a new ticket for that.

**Comment by Asalle** [comment]
Is `move-project-into-workspace` still considered for implementation? I would find it quite useful.
Thanks for the amazing feature all in all!
