### ISSUE TITLE
Handling Emacs 27

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#713]
- [x] Include Emacs 27 in CI build
- [x] Fix tests https://github.com/Alexander-Miller/treemacs/issues/707
- [x] Fix oversized/grey icons
- [x] Make use of new focus change functions https://github.com/Alexander-Miller/treemacs/issues/321
- [ ] Add option to only show fringe indicator when treemacs is focused https://github.com/Alexander-Miller/treemacs/issues/328
- [x] Integrate cfrs https://github.com/Alexander-Miller/treemacs/issues/242
